"""Translate `ingestion/schema.sql` into Postgres DDL.

**One schema file, translated - not two files kept in step.** The repo's own rule
elsewhere (competition keys in a table, alias maps in one module, the periods
vocabulary served over the API) is that a definition lives in exactly one place,
because a second copy drifts silently. A hand-maintained `schema.postgres.sql`
would be that second copy, and the first column added to `matches` would be added
to only one of them.

The translation is small because the schema is already close to portable: 262 of
its column declarations are `TEXT` or `INTEGER`, both of which Postgres accepts
unchanged, and there are no triggers, views, SQLite date functions or `COLLATE
NOCASE`. Two constructs need rewriting and one needs dropping:

* **`INTEGER PRIMARY KEY AUTOINCREMENT`** is SQLite's rowid alias. Postgres wants
  an identity column. `GENERATED BY DEFAULT` rather than `ALWAYS`, because the
  migration inserts the existing ids explicitly and `ALWAYS` would refuse them.
* **`) WITHOUT ROWID`** has no Postgres equivalent and is dropped. This is the one
  translation with a real cost, and it is worth knowing about: CLAUDE.md's
  measured "64 bytes per delivery, ~0.31 GB for the backfill" depended on it. In
  Postgres every row carries a ~24-byte header plus a separate primary-key index,
  so `deliveries` will be materially larger. Measured after loading, not guessed.
* **`AUTOINCREMENT` sequences need resetting** after an explicit-id load, or the
  next insert collides with row 1. `identity_resets` returns the statements.
"""

from __future__ import annotations

import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = PROJECT_ROOT / "ingestion" / "schema.sql"

# `INTEGER PRIMARY KEY AUTOINCREMENT` -> identity. Captured per line so the
# column name survives for `identity_resets` below.
_AUTOINC = re.compile(
    r"^(\s*)(\w+)\s+INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\s*,?\s*$",
    re.IGNORECASE | re.MULTILINE,
)
_WITHOUT_ROWID = re.compile(r"\)\s*WITHOUT\s+ROWID\s*;", re.IGNORECASE)
_CREATE_TABLE = re.compile(
    r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)", re.IGNORECASE
)


def translate(sql: str | None = None) -> str:
    """SQLite DDL in, Postgres DDL out."""
    text = sql if sql is not None else SCHEMA_PATH.read_text()

    def _identity(match: re.Match) -> str:
        indent, column = match.group(1), match.group(2)
        trailing = "," if match.group(0).rstrip().endswith(",") else ""
        return (
            f"{indent}{column} INTEGER GENERATED BY DEFAULT AS IDENTITY "
            f"PRIMARY KEY{trailing}"
        )

    text = _AUTOINC.sub(_identity, text)
    text = _WITHOUT_ROWID.sub(");", text)
    return text


def identity_columns(sql: str | None = None) -> list[tuple[str, str]]:
    """(table, column) for every identity column, for resetting sequences.

    Found by walking the ORIGINAL SQLite text: after translation the marker is
    gone, and matching on "GENERATED BY DEFAULT" would also catch anything a
    future schema declares that way for its own reasons.
    """
    text = sql if sql is not None else SCHEMA_PATH.read_text()
    out: list[tuple[str, str]] = []
    table = None
    for line in text.splitlines():
        found = _CREATE_TABLE.search(line)
        if found:
            table = found.group(1)
        hit = _AUTOINC.match(line)
        if hit and table:
            out.append((table, hit.group(2)))
    return out


def identity_resets(sql: str | None = None) -> list[str]:
    """Statements that move each identity sequence past the loaded rows.

    Required, not tidiness: the migration inserts existing primary keys
    explicitly, which leaves every sequence still at 1, so the first row the
    ingestion pipeline writes afterwards collides with an existing id. `coalesce`
    handles an empty table, where `max()` is NULL.
    """
    return [
        f"SELECT setval(pg_get_serial_sequence('{table}', '{column}'), "
        f"coalesce((SELECT max({column}) FROM {table}), 0) + 1, false);"
        for table, column in identity_columns(sql)
    ]


if __name__ == "__main__":  # pragma: no cover - a look at the output
    print(translate())
